"""集計と取得のテストが共有する最小のスナップショット。"""

from autoimmune_atlas.models import (
    CoreSnapshot,
)


def core_snapshot() -> CoreSnapshot:
    return {
        "schema": 2,
        "diseases": [
            {"id": "D1", "name": "Disease one", "status": "ready"},
            {"id": "D2", "name": "Disease two", "status": "ready"},
        ],
        "records": [
            {
                "disease_id": "D1",
                "disease": "Disease one",
                "drug_id": "A-SALT",
                "drug": "alpha salt",
                "canonical_drug_id": "A",
                "canonical_drug": "alpha",
                "drug_type": "Antibody",
                "stage": "PHASE_1",
                "target_id": "G1",
                "target": "Gene 1",
                "mechanism": "blocks",
                "references": [
                    {"source": "FDA", "ids": ["1"], "urls": ["https://example.test/1"]}
                ],
            },
            {
                "disease_id": "D1",
                "disease": "Disease one",
                "drug_id": "A",
                "drug": "alpha",
                "canonical_drug_id": "A",
                "canonical_drug": "alpha",
                "drug_type": "Antibody",
                "stage": "PHASE_3",
                "target_id": "G2",
                "target": "Gene 2",
                "mechanism": "blocks",
                "references": [],
            },
            {
                "disease_id": "D1",
                "disease": "Disease one",
                "drug_id": "B",
                "drug": "beta",
                "canonical_drug_id": "B",
                "canonical_drug": "beta",
                "drug_type": "Antibody",
                "stage": "PHASE_3",
                "target_id": "G3",
                "target": "Gene 3",
                "mechanism": "inhibits",
                "references": [],
            },
            {
                "disease_id": "D1",
                "disease": "Disease one",
                "drug_id": "U",
                "drug": "unknown",
                "canonical_drug_id": "U",
                "canonical_drug": "unknown",
                "drug_type": "Antibody",
                "stage": "PHASE_3",
                "target_id": "",
                "target": "Unknown",
                "mechanism": "",
                "references": [],
            },
            {
                "disease_id": "D2",
                "disease": "Disease two",
                "drug_id": "A",
                "drug": "alpha",
                "canonical_drug_id": "A",
                "canonical_drug": "alpha",
                "drug_type": "Antibody",
                "stage": "PHASE_1",
                "target_id": "G1",
                "target": "Gene 1",
                "mechanism": "blocks",
                "references": [],
            },
        ],
        "expression": {
            "G1": [
                {
                    "cell_id": "T4",
                    "cell": "CD4 T cell",
                    "median": 2.0,
                    "specificity_score": 0.75,
                    "parent_id": "LYMPH",
                    "parent": "Lymphocyte",
                    "ancestor_ids": ["CL_0000084"],
                },
                {
                    "cell_id": "T8",
                    "cell": "CD8 T cell",
                    "median": 0.1,
                    "specificity_score": 0.2,
                    "parent_id": "LYMPH",
                    "parent": "Lymphocyte",
                    "ancestor_ids": ["CL_0000084"],
                },
                {
                    "cell_id": "B1",
                    "cell": "B cell",
                    "median": 1.0,
                    "specificity_score": 0.8,
                    "parent_id": "B-GROUP",
                    "parent": "B lineage",
                    "ancestor_ids": [],
                },
                {
                    "cell_id": "X",
                    "cell": "Novel cell",
                    "median": 0.1,
                    "specificity_score": 0.1,
                    "parent_id": None,
                    "parent": None,
                    "ancestor_ids": [],
                },
            ],
            "G2": [
                {
                    "cell_id": "T4",
                    "cell": "CD4 T cell",
                    "median": 0.2,
                    "specificity_score": 0.1,
                    "parent_id": "LYMPH",
                    "parent": "Lymphocyte",
                    "ancestor_ids": ["CL_0000084"],
                },
                {
                    "cell_id": "T8",
                    "cell": "CD8 T cell",
                    "median": 3.0,
                    "specificity_score": 0.9,
                    "parent_id": "LYMPH",
                    "parent": "Lymphocyte",
                    "ancestor_ids": ["CL_0000084"],
                },
                {
                    "cell_id": "B1",
                    "cell": "B cell",
                    "median": 0.1,
                    "specificity_score": 0.1,
                    "parent_id": "B-GROUP",
                    "parent": "B lineage",
                    "ancestor_ids": [],
                },
                {
                    "cell_id": "X",
                    "cell": "Novel cell",
                    "median": 0.1,
                    "specificity_score": 0.1,
                    "parent_id": None,
                    "parent": None,
                    "ancestor_ids": [],
                },
            ],
            "G3": [
                {
                    "cell_id": "T4",
                    "cell": "CD4 T cell",
                    "median": None,
                    "specificity_score": None,
                    "parent_id": "LYMPH",
                    "parent": "Lymphocyte",
                    "ancestor_ids": ["CL_0000084"],
                },
                {
                    "cell_id": "T8",
                    "cell": "CD8 T cell",
                    "median": 0.1,
                    "specificity_score": 0.9,
                    "parent_id": "LYMPH",
                    "parent": "Lymphocyte",
                    "ancestor_ids": ["CL_0000084"],
                },
                {
                    "cell_id": "X",
                    "cell": "Novel cell",
                    "median": 2.0,
                    "specificity_score": 0.9,
                    "parent_id": None,
                    "parent": None,
                    "ancestor_ids": [],
                },
            ],
        },
    }
